# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet'

- task: UseDotNet@2
  displayName: 'Install NetCore 6.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: false

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test Jmw.DomainDrivenDesign.sln --configuration Release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]*%2c[*]GitVersionInformation"
  displayName: 'dotnet test $(buildConfiguration)'

